### ISSUE TITLE
Metaclass Conflict with Diffusers 0.23.1

### ISSUE THREAD

**Issue by JemiloII** [Bing-su/asdff#9]
Upgraded to Diffusers 0.23.1 and I get the following error. Not really sure what changed, maybe you have some insight? Much appreciated.

```
Traceback (most recent call last):
  File "D:\diffusion-ai\main2.py", line 8, in <module>
    from generation import shibiko_init, shibiko_create
  File "D:\diffusion-ai\generation.py", line 10, in <module>
    from asdff import AdPipeline
  File "D:\diffusion-ai\.venv\lib\site-packages\asdff\__init__.py", line 2, in <
module>
    from .sd import AdCnPipeline, AdPipeline
  File "D:\diffusion-ai\.venv\lib\site-packages\asdff\sd.py", line 18, in <modul
e>
    class AdPipeline(AdPipelineBase, StableDiffusionPipeline):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-s
trict) subclass of the metaclasses of all its bases
```

**Comment by Bing-su** [comment]
I ran `tests/test_pipeline.py` with diffusers 0.23.1 and verified that it runs without any issues.

**Comment by JemiloII** [comment]
I took another look and did a fresh install of all the packages. Maybe my diffusers lib had some artifacts from updating. Sorry and thanks for checking.
